// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

/**
 * <pre>
 **
 * 支付渠道
 * </pre>
 *
 * Protobuf enum {@code src.main.proto.Channel}
 */
public enum Channel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *支付宝支付
   * </pre>
   *
   * <code>ALI_PAY = 0;</code>
   */
  ALI_PAY(0),
  /**
   * <pre>
   *微信支付
   * </pre>
   *
   * <code>WX_PAY = 1;</code>
   */
  WX_PAY(1),
  /**
   * <pre>
   *银联支付
   * </pre>
   *
   * <code>UNION_PAY = 2;</code>
   */
  UNION_PAY(2),
  /**
   * <pre>
   *招商支付
   * </pre>
   *
   * <code>CMB_PAY = 3;</code>
   */
  CMB_PAY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *支付宝支付
   * </pre>
   *
   * <code>ALI_PAY = 0;</code>
   */
  public static final int ALI_PAY_VALUE = 0;
  /**
   * <pre>
   *微信支付
   * </pre>
   *
   * <code>WX_PAY = 1;</code>
   */
  public static final int WX_PAY_VALUE = 1;
  /**
   * <pre>
   *银联支付
   * </pre>
   *
   * <code>UNION_PAY = 2;</code>
   */
  public static final int UNION_PAY_VALUE = 2;
  /**
   * <pre>
   *招商支付
   * </pre>
   *
   * <code>CMB_PAY = 3;</code>
   */
  public static final int CMB_PAY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Channel valueOf(int value) {
    return forNumber(value);
  }

  public static Channel forNumber(int value) {
    switch (value) {
      case 0: return ALI_PAY;
      case 1: return WX_PAY;
      case 2: return UNION_PAY;
      case 3: return CMB_PAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Channel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Channel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Channel>() {
          public Channel findValueByNumber(int number) {
            return Channel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.zhongweixian.request.PayReq.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final Channel[] VALUES = values();

  public static Channel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Channel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:src.main.proto.Channel)
}

