// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *支付宝ID
   * </pre>
   *
   * <code>optional string aliAppId = 1;</code>
   */
  java.lang.String getAliAppId();
  /**
   * <pre>
   *支付宝ID
   * </pre>
   *
   * <code>optional string aliAppId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAliAppIdBytes();

  /**
   * <pre>
   *支付宝公钥
   * </pre>
   *
   * <code>optional string aliPublicKey = 2;</code>
   */
  java.lang.String getAliPublicKey();
  /**
   * <pre>
   *支付宝公钥
   * </pre>
   *
   * <code>optional string aliPublicKey = 2;</code>
   */
  com.google.protobuf.ByteString
      getAliPublicKeyBytes();

  /**
   * <pre>
   *商户私钥
   * </pre>
   *
   * <code>optional string privateKey = 3;</code>
   */
  java.lang.String getPrivateKey();
  /**
   * <pre>
   *商户私钥
   * </pre>
   *
   * <code>optional string privateKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getPrivateKeyBytes();

  /**
   * <pre>
   *微信应用ID
   * </pre>
   *
   * <code>optional string wxAppId = 4;</code>
   */
  java.lang.String getWxAppId();
  /**
   * <pre>
   *微信应用ID
   * </pre>
   *
   * <code>optional string wxAppId = 4;</code>
   */
  com.google.protobuf.ByteString
      getWxAppIdBytes();

  /**
   * <pre>
   *微信商户ID
   * </pre>
   *
   * <code>optional string wxMchId = 5;</code>
   */
  java.lang.String getWxMchId();
  /**
   * <pre>
   *微信商户ID
   * </pre>
   *
   * <code>optional string wxMchId = 5;</code>
   */
  com.google.protobuf.ByteString
      getWxMchIdBytes();

  /**
   * <pre>
   *微信公钥
   * </pre>
   *
   * <code>optional string wxKey = 6;</code>
   */
  java.lang.String getWxKey();
  /**
   * <pre>
   *微信公钥
   * </pre>
   *
   * <code>optional string wxKey = 6;</code>
   */
  com.google.protobuf.ByteString
      getWxKeyBytes();

  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  java.lang.String getNotifyUrl();
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  com.google.protobuf.ByteString
      getNotifyUrlBytes();

  /**
   * <pre>
   *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
   * </pre>
   *
   * <code>optional string certPath = 8;</code>
   */
  java.lang.String getCertPath();
  /**
   * <pre>
   *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
   * </pre>
   *
   * <code>optional string certPath = 8;</code>
   */
  com.google.protobuf.ByteString
      getCertPathBytes();
}
