// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

/**
 * <pre>
 **
 * config对象
 * </pre>
 *
 * Protobuf type {@code src.main.proto.Config}
 */
public  final class Config extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:src.main.proto.Config)
    ConfigOrBuilder {
  // Use Config.newBuilder() to construct.
  private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Config() {
    aliAppId_ = "";
    aliPublicKey_ = "";
    privateKey_ = "";
    wxAppId_ = "";
    wxMchId_ = "";
    wxKey_ = "";
    notifyUrl_ = "";
    certPath_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Config(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aliAppId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            aliPublicKey_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            privateKey_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            wxAppId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            wxMchId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            wxKey_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            notifyUrl_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            certPath_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zhongweixian.request.PayReq.internal_static_src_main_proto_Config_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zhongweixian.request.PayReq.internal_static_src_main_proto_Config_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zhongweixian.request.Config.class, org.zhongweixian.request.Config.Builder.class);
  }

  public static final int ALIAPPID_FIELD_NUMBER = 1;
  private volatile java.lang.Object aliAppId_;
  /**
   * <pre>
   *支付宝ID
   * </pre>
   *
   * <code>optional string aliAppId = 1;</code>
   */
  public java.lang.String getAliAppId() {
    java.lang.Object ref = aliAppId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aliAppId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *支付宝ID
   * </pre>
   *
   * <code>optional string aliAppId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAliAppIdBytes() {
    java.lang.Object ref = aliAppId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aliAppId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALIPUBLICKEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object aliPublicKey_;
  /**
   * <pre>
   *支付宝公钥
   * </pre>
   *
   * <code>optional string aliPublicKey = 2;</code>
   */
  public java.lang.String getAliPublicKey() {
    java.lang.Object ref = aliPublicKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aliPublicKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *支付宝公钥
   * </pre>
   *
   * <code>optional string aliPublicKey = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAliPublicKeyBytes() {
    java.lang.Object ref = aliPublicKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aliPublicKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIVATEKEY_FIELD_NUMBER = 3;
  private volatile java.lang.Object privateKey_;
  /**
   * <pre>
   *商户私钥
   * </pre>
   *
   * <code>optional string privateKey = 3;</code>
   */
  public java.lang.String getPrivateKey() {
    java.lang.Object ref = privateKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      privateKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *商户私钥
   * </pre>
   *
   * <code>optional string privateKey = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPrivateKeyBytes() {
    java.lang.Object ref = privateKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      privateKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WXAPPID_FIELD_NUMBER = 4;
  private volatile java.lang.Object wxAppId_;
  /**
   * <pre>
   *微信应用ID
   * </pre>
   *
   * <code>optional string wxAppId = 4;</code>
   */
  public java.lang.String getWxAppId() {
    java.lang.Object ref = wxAppId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wxAppId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *微信应用ID
   * </pre>
   *
   * <code>optional string wxAppId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getWxAppIdBytes() {
    java.lang.Object ref = wxAppId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wxAppId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WXMCHID_FIELD_NUMBER = 5;
  private volatile java.lang.Object wxMchId_;
  /**
   * <pre>
   *微信商户ID
   * </pre>
   *
   * <code>optional string wxMchId = 5;</code>
   */
  public java.lang.String getWxMchId() {
    java.lang.Object ref = wxMchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wxMchId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *微信商户ID
   * </pre>
   *
   * <code>optional string wxMchId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getWxMchIdBytes() {
    java.lang.Object ref = wxMchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wxMchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WXKEY_FIELD_NUMBER = 6;
  private volatile java.lang.Object wxKey_;
  /**
   * <pre>
   *微信公钥
   * </pre>
   *
   * <code>optional string wxKey = 6;</code>
   */
  public java.lang.String getWxKey() {
    java.lang.Object ref = wxKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wxKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *微信公钥
   * </pre>
   *
   * <code>optional string wxKey = 6;</code>
   */
  public com.google.protobuf.ByteString
      getWxKeyBytes() {
    java.lang.Object ref = wxKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wxKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFYURL_FIELD_NUMBER = 7;
  private volatile java.lang.Object notifyUrl_;
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  public java.lang.String getNotifyUrl() {
    java.lang.Object ref = notifyUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notifyUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNotifyUrlBytes() {
    java.lang.Object ref = notifyUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notifyUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CERTPATH_FIELD_NUMBER = 8;
  private volatile java.lang.Object certPath_;
  /**
   * <pre>
   *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
   * </pre>
   *
   * <code>optional string certPath = 8;</code>
   */
  public java.lang.String getCertPath() {
    java.lang.Object ref = certPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      certPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
   * </pre>
   *
   * <code>optional string certPath = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCertPathBytes() {
    java.lang.Object ref = certPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      certPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAliAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aliAppId_);
    }
    if (!getAliPublicKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, aliPublicKey_);
    }
    if (!getPrivateKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, privateKey_);
    }
    if (!getWxAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, wxAppId_);
    }
    if (!getWxMchIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, wxMchId_);
    }
    if (!getWxKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, wxKey_);
    }
    if (!getNotifyUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, notifyUrl_);
    }
    if (!getCertPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, certPath_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAliAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aliAppId_);
    }
    if (!getAliPublicKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, aliPublicKey_);
    }
    if (!getPrivateKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, privateKey_);
    }
    if (!getWxAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, wxAppId_);
    }
    if (!getWxMchIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, wxMchId_);
    }
    if (!getWxKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, wxKey_);
    }
    if (!getNotifyUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, notifyUrl_);
    }
    if (!getCertPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, certPath_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zhongweixian.request.Config)) {
      return super.equals(obj);
    }
    org.zhongweixian.request.Config other = (org.zhongweixian.request.Config) obj;

    boolean result = true;
    result = result && getAliAppId()
        .equals(other.getAliAppId());
    result = result && getAliPublicKey()
        .equals(other.getAliPublicKey());
    result = result && getPrivateKey()
        .equals(other.getPrivateKey());
    result = result && getWxAppId()
        .equals(other.getWxAppId());
    result = result && getWxMchId()
        .equals(other.getWxMchId());
    result = result && getWxKey()
        .equals(other.getWxKey());
    result = result && getNotifyUrl()
        .equals(other.getNotifyUrl());
    result = result && getCertPath()
        .equals(other.getCertPath());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ALIAPPID_FIELD_NUMBER;
    hash = (53 * hash) + getAliAppId().hashCode();
    hash = (37 * hash) + ALIPUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getAliPublicKey().hashCode();
    hash = (37 * hash) + PRIVATEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPrivateKey().hashCode();
    hash = (37 * hash) + WXAPPID_FIELD_NUMBER;
    hash = (53 * hash) + getWxAppId().hashCode();
    hash = (37 * hash) + WXMCHID_FIELD_NUMBER;
    hash = (53 * hash) + getWxMchId().hashCode();
    hash = (37 * hash) + WXKEY_FIELD_NUMBER;
    hash = (53 * hash) + getWxKey().hashCode();
    hash = (37 * hash) + NOTIFYURL_FIELD_NUMBER;
    hash = (53 * hash) + getNotifyUrl().hashCode();
    hash = (37 * hash) + CERTPATH_FIELD_NUMBER;
    hash = (53 * hash) + getCertPath().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zhongweixian.request.Config parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.request.Config parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.request.Config parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.request.Config parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.request.Config parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.Config parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.request.Config parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.Config parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.request.Config parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.Config parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zhongweixian.request.Config prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * config对象
   * </pre>
   *
   * Protobuf type {@code src.main.proto.Config}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:src.main.proto.Config)
      org.zhongweixian.request.ConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhongweixian.request.Config.class, org.zhongweixian.request.Config.Builder.class);
    }

    // Construct using org.zhongweixian.request.Config.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      aliAppId_ = "";

      aliPublicKey_ = "";

      privateKey_ = "";

      wxAppId_ = "";

      wxMchId_ = "";

      wxKey_ = "";

      notifyUrl_ = "";

      certPath_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_Config_descriptor;
    }

    public org.zhongweixian.request.Config getDefaultInstanceForType() {
      return org.zhongweixian.request.Config.getDefaultInstance();
    }

    public org.zhongweixian.request.Config build() {
      org.zhongweixian.request.Config result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.zhongweixian.request.Config buildPartial() {
      org.zhongweixian.request.Config result = new org.zhongweixian.request.Config(this);
      result.aliAppId_ = aliAppId_;
      result.aliPublicKey_ = aliPublicKey_;
      result.privateKey_ = privateKey_;
      result.wxAppId_ = wxAppId_;
      result.wxMchId_ = wxMchId_;
      result.wxKey_ = wxKey_;
      result.notifyUrl_ = notifyUrl_;
      result.certPath_ = certPath_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zhongweixian.request.Config) {
        return mergeFrom((org.zhongweixian.request.Config)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zhongweixian.request.Config other) {
      if (other == org.zhongweixian.request.Config.getDefaultInstance()) return this;
      if (!other.getAliAppId().isEmpty()) {
        aliAppId_ = other.aliAppId_;
        onChanged();
      }
      if (!other.getAliPublicKey().isEmpty()) {
        aliPublicKey_ = other.aliPublicKey_;
        onChanged();
      }
      if (!other.getPrivateKey().isEmpty()) {
        privateKey_ = other.privateKey_;
        onChanged();
      }
      if (!other.getWxAppId().isEmpty()) {
        wxAppId_ = other.wxAppId_;
        onChanged();
      }
      if (!other.getWxMchId().isEmpty()) {
        wxMchId_ = other.wxMchId_;
        onChanged();
      }
      if (!other.getWxKey().isEmpty()) {
        wxKey_ = other.wxKey_;
        onChanged();
      }
      if (!other.getNotifyUrl().isEmpty()) {
        notifyUrl_ = other.notifyUrl_;
        onChanged();
      }
      if (!other.getCertPath().isEmpty()) {
        certPath_ = other.certPath_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.zhongweixian.request.Config parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.zhongweixian.request.Config) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object aliAppId_ = "";
    /**
     * <pre>
     *支付宝ID
     * </pre>
     *
     * <code>optional string aliAppId = 1;</code>
     */
    public java.lang.String getAliAppId() {
      java.lang.Object ref = aliAppId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aliAppId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *支付宝ID
     * </pre>
     *
     * <code>optional string aliAppId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAliAppIdBytes() {
      java.lang.Object ref = aliAppId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aliAppId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *支付宝ID
     * </pre>
     *
     * <code>optional string aliAppId = 1;</code>
     */
    public Builder setAliAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aliAppId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付宝ID
     * </pre>
     *
     * <code>optional string aliAppId = 1;</code>
     */
    public Builder clearAliAppId() {
      
      aliAppId_ = getDefaultInstance().getAliAppId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付宝ID
     * </pre>
     *
     * <code>optional string aliAppId = 1;</code>
     */
    public Builder setAliAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aliAppId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object aliPublicKey_ = "";
    /**
     * <pre>
     *支付宝公钥
     * </pre>
     *
     * <code>optional string aliPublicKey = 2;</code>
     */
    public java.lang.String getAliPublicKey() {
      java.lang.Object ref = aliPublicKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aliPublicKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *支付宝公钥
     * </pre>
     *
     * <code>optional string aliPublicKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAliPublicKeyBytes() {
      java.lang.Object ref = aliPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aliPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *支付宝公钥
     * </pre>
     *
     * <code>optional string aliPublicKey = 2;</code>
     */
    public Builder setAliPublicKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aliPublicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付宝公钥
     * </pre>
     *
     * <code>optional string aliPublicKey = 2;</code>
     */
    public Builder clearAliPublicKey() {
      
      aliPublicKey_ = getDefaultInstance().getAliPublicKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付宝公钥
     * </pre>
     *
     * <code>optional string aliPublicKey = 2;</code>
     */
    public Builder setAliPublicKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aliPublicKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object privateKey_ = "";
    /**
     * <pre>
     *商户私钥
     * </pre>
     *
     * <code>optional string privateKey = 3;</code>
     */
    public java.lang.String getPrivateKey() {
      java.lang.Object ref = privateKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        privateKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *商户私钥
     * </pre>
     *
     * <code>optional string privateKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPrivateKeyBytes() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        privateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *商户私钥
     * </pre>
     *
     * <code>optional string privateKey = 3;</code>
     */
    public Builder setPrivateKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      privateKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户私钥
     * </pre>
     *
     * <code>optional string privateKey = 3;</code>
     */
    public Builder clearPrivateKey() {
      
      privateKey_ = getDefaultInstance().getPrivateKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户私钥
     * </pre>
     *
     * <code>optional string privateKey = 3;</code>
     */
    public Builder setPrivateKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      privateKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wxAppId_ = "";
    /**
     * <pre>
     *微信应用ID
     * </pre>
     *
     * <code>optional string wxAppId = 4;</code>
     */
    public java.lang.String getWxAppId() {
      java.lang.Object ref = wxAppId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wxAppId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *微信应用ID
     * </pre>
     *
     * <code>optional string wxAppId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getWxAppIdBytes() {
      java.lang.Object ref = wxAppId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wxAppId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *微信应用ID
     * </pre>
     *
     * <code>optional string wxAppId = 4;</code>
     */
    public Builder setWxAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wxAppId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *微信应用ID
     * </pre>
     *
     * <code>optional string wxAppId = 4;</code>
     */
    public Builder clearWxAppId() {
      
      wxAppId_ = getDefaultInstance().getWxAppId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *微信应用ID
     * </pre>
     *
     * <code>optional string wxAppId = 4;</code>
     */
    public Builder setWxAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wxAppId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wxMchId_ = "";
    /**
     * <pre>
     *微信商户ID
     * </pre>
     *
     * <code>optional string wxMchId = 5;</code>
     */
    public java.lang.String getWxMchId() {
      java.lang.Object ref = wxMchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wxMchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *微信商户ID
     * </pre>
     *
     * <code>optional string wxMchId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getWxMchIdBytes() {
      java.lang.Object ref = wxMchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wxMchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *微信商户ID
     * </pre>
     *
     * <code>optional string wxMchId = 5;</code>
     */
    public Builder setWxMchId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wxMchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *微信商户ID
     * </pre>
     *
     * <code>optional string wxMchId = 5;</code>
     */
    public Builder clearWxMchId() {
      
      wxMchId_ = getDefaultInstance().getWxMchId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *微信商户ID
     * </pre>
     *
     * <code>optional string wxMchId = 5;</code>
     */
    public Builder setWxMchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wxMchId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wxKey_ = "";
    /**
     * <pre>
     *微信公钥
     * </pre>
     *
     * <code>optional string wxKey = 6;</code>
     */
    public java.lang.String getWxKey() {
      java.lang.Object ref = wxKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wxKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *微信公钥
     * </pre>
     *
     * <code>optional string wxKey = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWxKeyBytes() {
      java.lang.Object ref = wxKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wxKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *微信公钥
     * </pre>
     *
     * <code>optional string wxKey = 6;</code>
     */
    public Builder setWxKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wxKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *微信公钥
     * </pre>
     *
     * <code>optional string wxKey = 6;</code>
     */
    public Builder clearWxKey() {
      
      wxKey_ = getDefaultInstance().getWxKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *微信公钥
     * </pre>
     *
     * <code>optional string wxKey = 6;</code>
     */
    public Builder setWxKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wxKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notifyUrl_ = "";
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public java.lang.String getNotifyUrl() {
      java.lang.Object ref = notifyUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notifyUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNotifyUrlBytes() {
      java.lang.Object ref = notifyUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notifyUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public Builder setNotifyUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notifyUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public Builder clearNotifyUrl() {
      
      notifyUrl_ = getDefaultInstance().getNotifyUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public Builder setNotifyUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notifyUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object certPath_ = "";
    /**
     * <pre>
     *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
     * </pre>
     *
     * <code>optional string certPath = 8;</code>
     */
    public java.lang.String getCertPath() {
      java.lang.Object ref = certPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        certPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
     * </pre>
     *
     * <code>optional string certPath = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCertPathBytes() {
      java.lang.Object ref = certPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        certPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
     * </pre>
     *
     * <code>optional string certPath = 8;</code>
     */
    public Builder setCertPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      certPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
     * </pre>
     *
     * <code>optional string certPath = 8;</code>
     */
    public Builder clearCertPath() {
      
      certPath_ = getDefaultInstance().getCertPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户证书 微信商户平台(pay.weixin.qq.com)--&gt;账户中心--&gt;账户设置--&gt;API安全--&gt;证书下载
     * </pre>
     *
     * <code>optional string certPath = 8;</code>
     */
    public Builder setCertPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      certPath_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:src.main.proto.Config)
  }

  // @@protoc_insertion_point(class_scope:src.main.proto.Config)
  private static final org.zhongweixian.request.Config DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zhongweixian.request.Config();
  }

  public static org.zhongweixian.request.Config getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Config>
      PARSER = new com.google.protobuf.AbstractParser<Config>() {
    public Config parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Config> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Config> getParserForType() {
    return PARSER;
  }

  public org.zhongweixian.request.Config getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

