// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  int getChannelValue();
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  org.zhongweixian.request.Channel getChannel();

  /**
   * <pre>
   *商户订单ID
   * </pre>
   *
   * <code>optional string orderNo = 2;</code>
   */
  java.lang.String getOrderNo();
  /**
   * <pre>
   *商户订单ID
   * </pre>
   *
   * <code>optional string orderNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();

  /**
   * <pre>
   *支付平台ID
   * </pre>
   *
   * <code>optional string orderId = 3;</code>
   */
  java.lang.String getOrderId();
  /**
   * <pre>
   *支付平台ID
   * </pre>
   *
   * <code>optional string orderId = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
