// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

/**
 * <pre>
 **
 * 支付请求对象
 * </pre>
 *
 * Protobuf type {@code src.main.proto.PayRequest}
 */
public  final class PayRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:src.main.proto.PayRequest)
    PayRequestOrBuilder {
  // Use PayRequest.newBuilder() to construct.
  private PayRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PayRequest() {
    channel_ = 0;
    payType_ = 0;
    amount_ = 0L;
    orderNo_ = "";
    clientIp_ = "";
    body_ = "";
    sign_ = "";
    signType_ = "";
    random_ = "";
    feeType_ = "";
    detail_ = "";
    requestUrl_ = "";
    notifyUrl_ = "";
    returnUrl_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PayRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            channel_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            payType_ = rawValue;
            break;
          }
          case 24: {

            amount_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            orderNo_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            clientIp_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            signType_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            random_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            feeType_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            detail_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            requestUrl_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            notifyUrl_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            returnUrl_ = s;
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
              ext_ = com.google.protobuf.MapField.newMapField(
                  ExtDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00004000;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            ext__ = input.readMessage(
                ExtDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            ext_.getMutableMap().put(
                ext__.getKey(), ext__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zhongweixian.request.PayReq.internal_static_src_main_proto_PayRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 15:
        return internalGetExt();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zhongweixian.request.PayReq.internal_static_src_main_proto_PayRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zhongweixian.request.PayRequest.class, org.zhongweixian.request.PayRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CHANNEL_FIELD_NUMBER = 1;
  private int channel_;
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  public int getChannelValue() {
    return channel_;
  }
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  public org.zhongweixian.request.Channel getChannel() {
    org.zhongweixian.request.Channel result = org.zhongweixian.request.Channel.valueOf(channel_);
    return result == null ? org.zhongweixian.request.Channel.UNRECOGNIZED : result;
  }

  public static final int PAYTYPE_FIELD_NUMBER = 2;
  private int payType_;
  /**
   * <pre>
   *类型
   * </pre>
   *
   * <code>optional .src.main.proto.PayType payType = 2;</code>
   */
  public int getPayTypeValue() {
    return payType_;
  }
  /**
   * <pre>
   *类型
   * </pre>
   *
   * <code>optional .src.main.proto.PayType payType = 2;</code>
   */
  public org.zhongweixian.request.PayType getPayType() {
    org.zhongweixian.request.PayType result = org.zhongweixian.request.PayType.valueOf(payType_);
    return result == null ? org.zhongweixian.request.PayType.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_FIELD_NUMBER = 3;
  private long amount_;
  /**
   * <pre>
   * 支付金额
   * </pre>
   *
   * <code>optional int64 amount = 3;</code>
   */
  public long getAmount() {
    return amount_;
  }

  public static final int ORDERNO_FIELD_NUMBER = 4;
  private volatile java.lang.Object orderNo_;
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string orderNo = 4;</code>
   */
  public java.lang.String getOrderNo() {
    java.lang.Object ref = orderNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string orderNo = 4;</code>
   */
  public com.google.protobuf.ByteString
      getOrderNoBytes() {
    java.lang.Object ref = orderNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTIP_FIELD_NUMBER = 5;
  private volatile java.lang.Object clientIp_;
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string clientIp = 5;</code>
   */
  public java.lang.String getClientIp() {
    java.lang.Object ref = clientIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string clientIp = 5;</code>
   */
  public com.google.protobuf.ByteString
      getClientIpBytes() {
    java.lang.Object ref = clientIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 6;
  private volatile java.lang.Object body_;
  /**
   * <pre>
   *商品描述
   * </pre>
   *
   * <code>optional string body = 6;</code>
   */
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *商品描述
   * </pre>
   *
   * <code>optional string body = 6;</code>
   */
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGN_FIELD_NUMBER = 7;
  private volatile java.lang.Object sign_;
  /**
   * <pre>
   *签名
   * </pre>
   *
   * <code>optional string sign = 7;</code>
   */
  public java.lang.String getSign() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *签名
   * </pre>
   *
   * <code>optional string sign = 7;</code>
   */
  public com.google.protobuf.ByteString
      getSignBytes() {
    java.lang.Object ref = sign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNTYPE_FIELD_NUMBER = 8;
  private volatile java.lang.Object signType_;
  /**
   * <pre>
   *签名类型
   * </pre>
   *
   * <code>optional string signType = 8;</code>
   */
  public java.lang.String getSignType() {
    java.lang.Object ref = signType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *签名类型
   * </pre>
   *
   * <code>optional string signType = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSignTypeBytes() {
    java.lang.Object ref = signType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANDOM_FIELD_NUMBER = 9;
  private volatile java.lang.Object random_;
  /**
   * <pre>
   *随机数
   * </pre>
   *
   * <code>optional string random = 9;</code>
   */
  public java.lang.String getRandom() {
    java.lang.Object ref = random_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      random_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *随机数
   * </pre>
   *
   * <code>optional string random = 9;</code>
   */
  public com.google.protobuf.ByteString
      getRandomBytes() {
    java.lang.Object ref = random_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      random_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEETYPE_FIELD_NUMBER = 10;
  private volatile java.lang.Object feeType_;
  /**
   * <pre>
   *货币种类
   * </pre>
   *
   * <code>optional string feeType = 10;</code>
   */
  public java.lang.String getFeeType() {
    java.lang.Object ref = feeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      feeType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *货币种类
   * </pre>
   *
   * <code>optional string feeType = 10;</code>
   */
  public com.google.protobuf.ByteString
      getFeeTypeBytes() {
    java.lang.Object ref = feeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      feeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAIL_FIELD_NUMBER = 11;
  private volatile java.lang.Object detail_;
  /**
   * <pre>
   *商品详情
   * </pre>
   *
   * <code>optional string detail = 11;</code>
   */
  public java.lang.String getDetail() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      detail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *商品详情
   * </pre>
   *
   * <code>optional string detail = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDetailBytes() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      detail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTURL_FIELD_NUMBER = 12;
  private volatile java.lang.Object requestUrl_;
  /**
   * <pre>
   *请求地址
   * </pre>
   *
   * <code>optional string requestUrl = 12;</code>
   */
  public java.lang.String getRequestUrl() {
    java.lang.Object ref = requestUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *请求地址
   * </pre>
   *
   * <code>optional string requestUrl = 12;</code>
   */
  public com.google.protobuf.ByteString
      getRequestUrlBytes() {
    java.lang.Object ref = requestUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFYURL_FIELD_NUMBER = 13;
  private volatile java.lang.Object notifyUrl_;
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 13;</code>
   */
  public java.lang.String getNotifyUrl() {
    java.lang.Object ref = notifyUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notifyUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 13;</code>
   */
  public com.google.protobuf.ByteString
      getNotifyUrlBytes() {
    java.lang.Object ref = notifyUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notifyUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNURL_FIELD_NUMBER = 14;
  private volatile java.lang.Object returnUrl_;
  /**
   * <pre>
   *前端返回地址
   * </pre>
   *
   * <code>optional string returnUrl = 14;</code>
   */
  public java.lang.String getReturnUrl() {
    java.lang.Object ref = returnUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *前端返回地址
   * </pre>
   *
   * <code>optional string returnUrl = 14;</code>
   */
  public com.google.protobuf.ByteString
      getReturnUrlBytes() {
    java.lang.Object ref = returnUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXT_FIELD_NUMBER = 15;
  private static final class ExtDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.zhongweixian.request.PayReq.internal_static_src_main_proto_PayRequest_ExtEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> ext_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExt() {
    if (ext_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtDefaultEntryHolder.defaultEntry);
    }
    return ext_;
  }

  public int getExtCount() {
    return internalGetExt().getMap().size();
  }
  /**
   * <pre>
   *扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 15;</code>
   */

  public boolean containsExt(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetExt().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExt() {
    return getExtMap();
  }
  /**
   * <pre>
   *扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 15;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
    return internalGetExt().getMap();
  }
  /**
   * <pre>
   *扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 15;</code>
   */

  public java.lang.String getExtOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExt().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *扩展字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; ext = 15;</code>
   */

  public java.lang.String getExtOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExt().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (channel_ != org.zhongweixian.request.Channel.ALI_PAY.getNumber()) {
      output.writeEnum(1, channel_);
    }
    if (payType_ != org.zhongweixian.request.PayType.ALI_H5.getNumber()) {
      output.writeEnum(2, payType_);
    }
    if (amount_ != 0L) {
      output.writeInt64(3, amount_);
    }
    if (!getOrderNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderNo_);
    }
    if (!getClientIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientIp_);
    }
    if (!getBodyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, body_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sign_);
    }
    if (!getSignTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, signType_);
    }
    if (!getRandomBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, random_);
    }
    if (!getFeeTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, feeType_);
    }
    if (!getDetailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, detail_);
    }
    if (!getRequestUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, requestUrl_);
    }
    if (!getNotifyUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, notifyUrl_);
    }
    if (!getReturnUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, returnUrl_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetExt(),
        ExtDefaultEntryHolder.defaultEntry,
        15);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (channel_ != org.zhongweixian.request.Channel.ALI_PAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, channel_);
    }
    if (payType_ != org.zhongweixian.request.PayType.ALI_H5.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, payType_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, amount_);
    }
    if (!getOrderNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, orderNo_);
    }
    if (!getClientIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientIp_);
    }
    if (!getBodyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, body_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sign_);
    }
    if (!getSignTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, signType_);
    }
    if (!getRandomBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, random_);
    }
    if (!getFeeTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, feeType_);
    }
    if (!getDetailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, detail_);
    }
    if (!getRequestUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, requestUrl_);
    }
    if (!getNotifyUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, notifyUrl_);
    }
    if (!getReturnUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, returnUrl_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExt().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      ext__ = ExtDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, ext__);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zhongweixian.request.PayRequest)) {
      return super.equals(obj);
    }
    org.zhongweixian.request.PayRequest other = (org.zhongweixian.request.PayRequest) obj;

    boolean result = true;
    result = result && channel_ == other.channel_;
    result = result && payType_ == other.payType_;
    result = result && (getAmount()
        == other.getAmount());
    result = result && getOrderNo()
        .equals(other.getOrderNo());
    result = result && getClientIp()
        .equals(other.getClientIp());
    result = result && getBody()
        .equals(other.getBody());
    result = result && getSign()
        .equals(other.getSign());
    result = result && getSignType()
        .equals(other.getSignType());
    result = result && getRandom()
        .equals(other.getRandom());
    result = result && getFeeType()
        .equals(other.getFeeType());
    result = result && getDetail()
        .equals(other.getDetail());
    result = result && getRequestUrl()
        .equals(other.getRequestUrl());
    result = result && getNotifyUrl()
        .equals(other.getNotifyUrl());
    result = result && getReturnUrl()
        .equals(other.getReturnUrl());
    result = result && internalGetExt().equals(
        other.internalGetExt());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
    hash = (53 * hash) + channel_;
    hash = (37 * hash) + PAYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + payType_;
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (37 * hash) + ORDERNO_FIELD_NUMBER;
    hash = (53 * hash) + getOrderNo().hashCode();
    hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
    hash = (53 * hash) + getClientIp().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (37 * hash) + SIGNTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSignType().hashCode();
    hash = (37 * hash) + RANDOM_FIELD_NUMBER;
    hash = (53 * hash) + getRandom().hashCode();
    hash = (37 * hash) + FEETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFeeType().hashCode();
    hash = (37 * hash) + DETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getDetail().hashCode();
    hash = (37 * hash) + REQUESTURL_FIELD_NUMBER;
    hash = (53 * hash) + getRequestUrl().hashCode();
    hash = (37 * hash) + NOTIFYURL_FIELD_NUMBER;
    hash = (53 * hash) + getNotifyUrl().hashCode();
    hash = (37 * hash) + RETURNURL_FIELD_NUMBER;
    hash = (53 * hash) + getReturnUrl().hashCode();
    if (!internalGetExt().getMap().isEmpty()) {
      hash = (37 * hash) + EXT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zhongweixian.request.PayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.request.PayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.PayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.PayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zhongweixian.request.PayRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 支付请求对象
   * </pre>
   *
   * Protobuf type {@code src.main.proto.PayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:src.main.proto.PayRequest)
      org.zhongweixian.request.PayRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_PayRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 15:
          return internalGetExt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 15:
          return internalGetMutableExt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_PayRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhongweixian.request.PayRequest.class, org.zhongweixian.request.PayRequest.Builder.class);
    }

    // Construct using org.zhongweixian.request.PayRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      channel_ = 0;

      payType_ = 0;

      amount_ = 0L;

      orderNo_ = "";

      clientIp_ = "";

      body_ = "";

      sign_ = "";

      signType_ = "";

      random_ = "";

      feeType_ = "";

      detail_ = "";

      requestUrl_ = "";

      notifyUrl_ = "";

      returnUrl_ = "";

      internalGetMutableExt().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_PayRequest_descriptor;
    }

    public org.zhongweixian.request.PayRequest getDefaultInstanceForType() {
      return org.zhongweixian.request.PayRequest.getDefaultInstance();
    }

    public org.zhongweixian.request.PayRequest build() {
      org.zhongweixian.request.PayRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.zhongweixian.request.PayRequest buildPartial() {
      org.zhongweixian.request.PayRequest result = new org.zhongweixian.request.PayRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.channel_ = channel_;
      result.payType_ = payType_;
      result.amount_ = amount_;
      result.orderNo_ = orderNo_;
      result.clientIp_ = clientIp_;
      result.body_ = body_;
      result.sign_ = sign_;
      result.signType_ = signType_;
      result.random_ = random_;
      result.feeType_ = feeType_;
      result.detail_ = detail_;
      result.requestUrl_ = requestUrl_;
      result.notifyUrl_ = notifyUrl_;
      result.returnUrl_ = returnUrl_;
      result.ext_ = internalGetExt();
      result.ext_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zhongweixian.request.PayRequest) {
        return mergeFrom((org.zhongweixian.request.PayRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zhongweixian.request.PayRequest other) {
      if (other == org.zhongweixian.request.PayRequest.getDefaultInstance()) return this;
      if (other.channel_ != 0) {
        setChannelValue(other.getChannelValue());
      }
      if (other.payType_ != 0) {
        setPayTypeValue(other.getPayTypeValue());
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      if (!other.getOrderNo().isEmpty()) {
        orderNo_ = other.orderNo_;
        onChanged();
      }
      if (!other.getClientIp().isEmpty()) {
        clientIp_ = other.clientIp_;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      if (!other.getSignType().isEmpty()) {
        signType_ = other.signType_;
        onChanged();
      }
      if (!other.getRandom().isEmpty()) {
        random_ = other.random_;
        onChanged();
      }
      if (!other.getFeeType().isEmpty()) {
        feeType_ = other.feeType_;
        onChanged();
      }
      if (!other.getDetail().isEmpty()) {
        detail_ = other.detail_;
        onChanged();
      }
      if (!other.getRequestUrl().isEmpty()) {
        requestUrl_ = other.requestUrl_;
        onChanged();
      }
      if (!other.getNotifyUrl().isEmpty()) {
        notifyUrl_ = other.notifyUrl_;
        onChanged();
      }
      if (!other.getReturnUrl().isEmpty()) {
        returnUrl_ = other.returnUrl_;
        onChanged();
      }
      internalGetMutableExt().mergeFrom(
          other.internalGetExt());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.zhongweixian.request.PayRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.zhongweixian.request.PayRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int channel_ = 0;
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public int getChannelValue() {
      return channel_;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public Builder setChannelValue(int value) {
      channel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public org.zhongweixian.request.Channel getChannel() {
      org.zhongweixian.request.Channel result = org.zhongweixian.request.Channel.valueOf(channel_);
      return result == null ? org.zhongweixian.request.Channel.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public Builder setChannel(org.zhongweixian.request.Channel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      channel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public Builder clearChannel() {
      
      channel_ = 0;
      onChanged();
      return this;
    }

    private int payType_ = 0;
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>optional .src.main.proto.PayType payType = 2;</code>
     */
    public int getPayTypeValue() {
      return payType_;
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>optional .src.main.proto.PayType payType = 2;</code>
     */
    public Builder setPayTypeValue(int value) {
      payType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>optional .src.main.proto.PayType payType = 2;</code>
     */
    public org.zhongweixian.request.PayType getPayType() {
      org.zhongweixian.request.PayType result = org.zhongweixian.request.PayType.valueOf(payType_);
      return result == null ? org.zhongweixian.request.PayType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>optional .src.main.proto.PayType payType = 2;</code>
     */
    public Builder setPayType(org.zhongweixian.request.PayType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      payType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>optional .src.main.proto.PayType payType = 2;</code>
     */
    public Builder clearPayType() {
      
      payType_ = 0;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <pre>
     * 支付金额
     * </pre>
     *
     * <code>optional int64 amount = 3;</code>
     */
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * 支付金额
     * </pre>
     *
     * <code>optional int64 amount = 3;</code>
     */
    public Builder setAmount(long value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 支付金额
     * </pre>
     *
     * <code>optional int64 amount = 3;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object orderNo_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string orderNo = 4;</code>
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string orderNo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string orderNo = 4;</code>
     */
    public Builder setOrderNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string orderNo = 4;</code>
     */
    public Builder clearOrderNo() {
      
      orderNo_ = getDefaultInstance().getOrderNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string orderNo = 4;</code>
     */
    public Builder setOrderNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientIp_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string clientIp = 5;</code>
     */
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string clientIp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string clientIp = 5;</code>
     */
    public Builder setClientIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string clientIp = 5;</code>
     */
    public Builder clearClientIp() {
      
      clientIp_ = getDefaultInstance().getClientIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string clientIp = 5;</code>
     */
    public Builder setClientIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <pre>
     *商品描述
     * </pre>
     *
     * <code>optional string body = 6;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *商品描述
     * </pre>
     *
     * <code>optional string body = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *商品描述
     * </pre>
     *
     * <code>optional string body = 6;</code>
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商品描述
     * </pre>
     *
     * <code>optional string body = 6;</code>
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商品描述
     * </pre>
     *
     * <code>optional string body = 6;</code>
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sign_ = "";
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string sign = 7;</code>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string sign = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string sign = 7;</code>
     */
    public Builder setSign(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string sign = 7;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string sign = 7;</code>
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sign_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object signType_ = "";
    /**
     * <pre>
     *签名类型
     * </pre>
     *
     * <code>optional string signType = 8;</code>
     */
    public java.lang.String getSignType() {
      java.lang.Object ref = signType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *签名类型
     * </pre>
     *
     * <code>optional string signType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSignTypeBytes() {
      java.lang.Object ref = signType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *签名类型
     * </pre>
     *
     * <code>optional string signType = 8;</code>
     */
    public Builder setSignType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *签名类型
     * </pre>
     *
     * <code>optional string signType = 8;</code>
     */
    public Builder clearSignType() {
      
      signType_ = getDefaultInstance().getSignType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *签名类型
     * </pre>
     *
     * <code>optional string signType = 8;</code>
     */
    public Builder setSignTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object random_ = "";
    /**
     * <pre>
     *随机数
     * </pre>
     *
     * <code>optional string random = 9;</code>
     */
    public java.lang.String getRandom() {
      java.lang.Object ref = random_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        random_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *随机数
     * </pre>
     *
     * <code>optional string random = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRandomBytes() {
      java.lang.Object ref = random_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        random_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *随机数
     * </pre>
     *
     * <code>optional string random = 9;</code>
     */
    public Builder setRandom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      random_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *随机数
     * </pre>
     *
     * <code>optional string random = 9;</code>
     */
    public Builder clearRandom() {
      
      random_ = getDefaultInstance().getRandom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *随机数
     * </pre>
     *
     * <code>optional string random = 9;</code>
     */
    public Builder setRandomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      random_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object feeType_ = "";
    /**
     * <pre>
     *货币种类
     * </pre>
     *
     * <code>optional string feeType = 10;</code>
     */
    public java.lang.String getFeeType() {
      java.lang.Object ref = feeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *货币种类
     * </pre>
     *
     * <code>optional string feeType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFeeTypeBytes() {
      java.lang.Object ref = feeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *货币种类
     * </pre>
     *
     * <code>optional string feeType = 10;</code>
     */
    public Builder setFeeType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      feeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *货币种类
     * </pre>
     *
     * <code>optional string feeType = 10;</code>
     */
    public Builder clearFeeType() {
      
      feeType_ = getDefaultInstance().getFeeType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *货币种类
     * </pre>
     *
     * <code>optional string feeType = 10;</code>
     */
    public Builder setFeeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      feeType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object detail_ = "";
    /**
     * <pre>
     *商品详情
     * </pre>
     *
     * <code>optional string detail = 11;</code>
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *商品详情
     * </pre>
     *
     * <code>optional string detail = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *商品详情
     * </pre>
     *
     * <code>optional string detail = 11;</code>
     */
    public Builder setDetail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      detail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商品详情
     * </pre>
     *
     * <code>optional string detail = 11;</code>
     */
    public Builder clearDetail() {
      
      detail_ = getDefaultInstance().getDetail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商品详情
     * </pre>
     *
     * <code>optional string detail = 11;</code>
     */
    public Builder setDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      detail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestUrl_ = "";
    /**
     * <pre>
     *请求地址
     * </pre>
     *
     * <code>optional string requestUrl = 12;</code>
     */
    public java.lang.String getRequestUrl() {
      java.lang.Object ref = requestUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *请求地址
     * </pre>
     *
     * <code>optional string requestUrl = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRequestUrlBytes() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *请求地址
     * </pre>
     *
     * <code>optional string requestUrl = 12;</code>
     */
    public Builder setRequestUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求地址
     * </pre>
     *
     * <code>optional string requestUrl = 12;</code>
     */
    public Builder clearRequestUrl() {
      
      requestUrl_ = getDefaultInstance().getRequestUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求地址
     * </pre>
     *
     * <code>optional string requestUrl = 12;</code>
     */
    public Builder setRequestUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notifyUrl_ = "";
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 13;</code>
     */
    public java.lang.String getNotifyUrl() {
      java.lang.Object ref = notifyUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notifyUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 13;</code>
     */
    public com.google.protobuf.ByteString
        getNotifyUrlBytes() {
      java.lang.Object ref = notifyUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notifyUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 13;</code>
     */
    public Builder setNotifyUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notifyUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 13;</code>
     */
    public Builder clearNotifyUrl() {
      
      notifyUrl_ = getDefaultInstance().getNotifyUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 13;</code>
     */
    public Builder setNotifyUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notifyUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnUrl_ = "";
    /**
     * <pre>
     *前端返回地址
     * </pre>
     *
     * <code>optional string returnUrl = 14;</code>
     */
    public java.lang.String getReturnUrl() {
      java.lang.Object ref = returnUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *前端返回地址
     * </pre>
     *
     * <code>optional string returnUrl = 14;</code>
     */
    public com.google.protobuf.ByteString
        getReturnUrlBytes() {
      java.lang.Object ref = returnUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *前端返回地址
     * </pre>
     *
     * <code>optional string returnUrl = 14;</code>
     */
    public Builder setReturnUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *前端返回地址
     * </pre>
     *
     * <code>optional string returnUrl = 14;</code>
     */
    public Builder clearReturnUrl() {
      
      returnUrl_ = getDefaultInstance().getReturnUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *前端返回地址
     * </pre>
     *
     * <code>optional string returnUrl = 14;</code>
     */
    public Builder setReturnUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnUrl_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> ext_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExt() {
      if (ext_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtDefaultEntryHolder.defaultEntry);
      }
      return ext_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableExt() {
      onChanged();;
      if (ext_ == null) {
        ext_ = com.google.protobuf.MapField.newMapField(
            ExtDefaultEntryHolder.defaultEntry);
      }
      if (!ext_.isMutable()) {
        ext_ = ext_.copy();
      }
      return ext_;
    }

    public int getExtCount() {
      return internalGetExt().getMap().size();
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */

    public boolean containsExt(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExt() {
      return getExtMap();
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getExtMap() {
      return internalGetExt().getMap();
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */

    public java.lang.String getExtOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */

    public java.lang.String getExtOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExt().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearExt() {
      getMutableExt().clear();
      return this;
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */

    public Builder removeExt(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      getMutableExt().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableExt() {
      return internalGetMutableExt().getMutableMap();
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */
    public Builder putExt(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      getMutableExt().put(key, value);
      return this;
    }
    /**
     * <pre>
     *扩展字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 15;</code>
     */

    public Builder putAllExt(
        java.util.Map<java.lang.String, java.lang.String> values) {
      getMutableExt().putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:src.main.proto.PayRequest)
  }

  // @@protoc_insertion_point(class_scope:src.main.proto.PayRequest)
  private static final org.zhongweixian.request.PayRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zhongweixian.request.PayRequest();
  }

  public static org.zhongweixian.request.PayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PayRequest>
      PARSER = new com.google.protobuf.AbstractParser<PayRequest>() {
    public PayRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PayRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PayRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PayRequest> getParserForType() {
    return PARSER;
  }

  public org.zhongweixian.request.PayRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

