// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

public final class PayReq {
  private PayReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_PayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_PayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_PayRequest_ExtEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_PayRequest_ExtEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_RefundRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_RefundRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_VerifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_VerifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014PayReq.proto\022\016src.main.proto\"\212\003\n\nPayRe" +
      "quest\022(\n\007channel\030\001 \001(\0162\027.src.main.proto." +
      "Channel\022(\n\007payType\030\002 \001(\0162\027.src.main.prot" +
      "o.PayType\022\016\n\006amount\030\003 \001(\003\022\017\n\007orderNo\030\004 \001" +
      "(\t\022\020\n\010clientIp\030\005 \001(\t\022\014\n\004body\030\006 \001(\t\022\014\n\004si" +
      "gn\030\007 \001(\t\022\020\n\010signType\030\010 \001(\t\022\016\n\006random\030\t \001" +
      "(\t\022\017\n\007feeType\030\n \001(\t\022\016\n\006detail\030\013 \001(\t\022\022\n\nr" +
      "equestUrl\030\014 \001(\t\022\021\n\tnotifyUrl\030\r \001(\t\022\021\n\tre" +
      "turnUrl\030\016 \001(\t\0220\n\003ext\030\017 \003(\0132#.src.main.pr" +
      "oto.PayRequest.ExtEntry\032*\n\010ExtEntry\022\013\n\003k",
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\271\001\n\rRefundRe" +
      "quest\022(\n\007channel\030\001 \001(\0162\027.src.main.proto." +
      "Channel\022\017\n\007orderNo\030\002 \001(\t\022\017\n\007orderId\030\003 \001(" +
      "\t\022\020\n\010refundNo\030\004 \001(\t\022\020\n\010totalFee\030\005 \001(\003\022\021\n" +
      "\trefundFee\030\006 \001(\003\022\021\n\tnotifyUrl\030\007 \001(\t\022\022\n\nr" +
      "efundDesc\030\t \001(\t\"g\n\rVerifyRequest\022(\n\007chan" +
      "nel\030\001 \001(\0162\027.src.main.proto.Channel\022\014\n\004bo" +
      "dy\030\002 \001(\t\022\021\n\tsignature\030\003 \001(\t\022\013\n\003key\030\004 \001(\t" +
      "\"Z\n\014OrderRequest\022(\n\007channel\030\001 \001(\0162\027.src." +
      "main.proto.Channel\022\017\n\007orderNo\030\002 \001(\t\022\017\n\007o",
      "rderId\030\003 \001(\t\"\232\001\n\006Config\022\020\n\010aliAppId\030\001 \001(" +
      "\t\022\024\n\014aliPublicKey\030\002 \001(\t\022\022\n\nprivateKey\030\003 " +
      "\001(\t\022\017\n\007wxAppId\030\004 \001(\t\022\017\n\007wxMchId\030\005 \001(\t\022\r\n" +
      "\005wxKey\030\006 \001(\t\022\021\n\tnotifyUrl\030\007 \001(\t\022\020\n\010certP" +
      "ath\030\010 \001(\t*>\n\007Channel\022\013\n\007ALI_PAY\020\000\022\n\n\006WX_" +
      "PAY\020\001\022\r\n\tUNION_PAY\020\002\022\013\n\007CMB_PAY\020\003*\220\001\n\007Pa" +
      "yType\022\n\n\006ALI_H5\020\000\022\013\n\007ALI_WEB\020\001\022\013\n\007ALI_AP" +
      "P\020\002\022\014\n\010ALI_FACE\020\003\022\022\n\016ALI_PRE_CREATE\020\004\022\014\n" +
      "\010WX_MICRO\020\005\022\t\n\005WX_H5\020\006\022\t\n\005WX_JS\020\007\022\r\n\tWX_" +
      "QRCODE\020\010\022\n\n\006WX_APP\020\tB\037\n\030org.zhongweixian",
      ".requestP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_src_main_proto_PayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_src_main_proto_PayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_PayRequest_descriptor,
        new java.lang.String[] { "Channel", "PayType", "Amount", "OrderNo", "ClientIp", "Body", "Sign", "SignType", "Random", "FeeType", "Detail", "RequestUrl", "NotifyUrl", "ReturnUrl", "Ext", });
    internal_static_src_main_proto_PayRequest_ExtEntry_descriptor =
      internal_static_src_main_proto_PayRequest_descriptor.getNestedTypes().get(0);
    internal_static_src_main_proto_PayRequest_ExtEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_PayRequest_ExtEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_src_main_proto_RefundRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_src_main_proto_RefundRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_RefundRequest_descriptor,
        new java.lang.String[] { "Channel", "OrderNo", "OrderId", "RefundNo", "TotalFee", "RefundFee", "NotifyUrl", "RefundDesc", });
    internal_static_src_main_proto_VerifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_src_main_proto_VerifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_VerifyRequest_descriptor,
        new java.lang.String[] { "Channel", "Body", "Signature", "Key", });
    internal_static_src_main_proto_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_src_main_proto_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_OrderRequest_descriptor,
        new java.lang.String[] { "Channel", "OrderNo", "OrderId", });
    internal_static_src_main_proto_Config_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_src_main_proto_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_Config_descriptor,
        new java.lang.String[] { "AliAppId", "AliPublicKey", "PrivateKey", "WxAppId", "WxMchId", "WxKey", "NotifyUrl", "CertPath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
