// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

/**
 * <pre>
 **
 * 支付类型
 * </pre>
 *
 * Protobuf enum {@code src.main.proto.PayType}
 */
public enum PayType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *手机网站支付
   * </pre>
   *
   * <code>ALI_H5 = 0;</code>
   */
  ALI_H5(0),
  /**
   * <pre>
   *支付宝电脑网站支付
   * </pre>
   *
   * <code>ALI_WEB = 1;</code>
   */
  ALI_WEB(1),
  /**
   * <pre>
   *APP支付
   * </pre>
   *
   * <code>ALI_APP = 2;</code>
   */
  ALI_APP(2),
  /**
   * <pre>
   *当面付[商家主动扫码,支付宝用户展示二维码]
   * </pre>
   *
   * <code>ALI_FACE = 3;</code>
   */
  ALI_FACE(3),
  /**
   * <pre>
   *商家展示二维码，用户扫码支付
   * </pre>
   *
   * <code>ALI_PRE_CREATE = 4;</code>
   */
  ALI_PRE_CREATE(4),
  /**
   * <pre>
   *刷卡支付[商家主动扫码,微信用户展示二维码]
   * </pre>
   *
   * <code>WX_MICRO = 5;</code>
   */
  WX_MICRO(5),
  /**
   * <pre>
   *H5支付
   * </pre>
   *
   * <code>WX_H5 = 6;</code>
   */
  WX_H5(6),
  /**
   * <pre>
   *公众号支付
   * </pre>
   *
   * <code>WX_JS = 7;</code>
   */
  WX_JS(7),
  /**
   * <pre>
   *扫码支付
   * </pre>
   *
   * <code>WX_QRCODE = 8;</code>
   */
  WX_QRCODE(8),
  /**
   * <pre>
   *微信APP支付
   * </pre>
   *
   * <code>WX_APP = 9;</code>
   */
  WX_APP(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *手机网站支付
   * </pre>
   *
   * <code>ALI_H5 = 0;</code>
   */
  public static final int ALI_H5_VALUE = 0;
  /**
   * <pre>
   *支付宝电脑网站支付
   * </pre>
   *
   * <code>ALI_WEB = 1;</code>
   */
  public static final int ALI_WEB_VALUE = 1;
  /**
   * <pre>
   *APP支付
   * </pre>
   *
   * <code>ALI_APP = 2;</code>
   */
  public static final int ALI_APP_VALUE = 2;
  /**
   * <pre>
   *当面付[商家主动扫码,支付宝用户展示二维码]
   * </pre>
   *
   * <code>ALI_FACE = 3;</code>
   */
  public static final int ALI_FACE_VALUE = 3;
  /**
   * <pre>
   *商家展示二维码，用户扫码支付
   * </pre>
   *
   * <code>ALI_PRE_CREATE = 4;</code>
   */
  public static final int ALI_PRE_CREATE_VALUE = 4;
  /**
   * <pre>
   *刷卡支付[商家主动扫码,微信用户展示二维码]
   * </pre>
   *
   * <code>WX_MICRO = 5;</code>
   */
  public static final int WX_MICRO_VALUE = 5;
  /**
   * <pre>
   *H5支付
   * </pre>
   *
   * <code>WX_H5 = 6;</code>
   */
  public static final int WX_H5_VALUE = 6;
  /**
   * <pre>
   *公众号支付
   * </pre>
   *
   * <code>WX_JS = 7;</code>
   */
  public static final int WX_JS_VALUE = 7;
  /**
   * <pre>
   *扫码支付
   * </pre>
   *
   * <code>WX_QRCODE = 8;</code>
   */
  public static final int WX_QRCODE_VALUE = 8;
  /**
   * <pre>
   *微信APP支付
   * </pre>
   *
   * <code>WX_APP = 9;</code>
   */
  public static final int WX_APP_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PayType valueOf(int value) {
    return forNumber(value);
  }

  public static PayType forNumber(int value) {
    switch (value) {
      case 0: return ALI_H5;
      case 1: return ALI_WEB;
      case 2: return ALI_APP;
      case 3: return ALI_FACE;
      case 4: return ALI_PRE_CREATE;
      case 5: return WX_MICRO;
      case 6: return WX_H5;
      case 7: return WX_JS;
      case 8: return WX_QRCODE;
      case 9: return WX_APP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PayType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PayType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PayType>() {
          public PayType findValueByNumber(int number) {
            return PayType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.zhongweixian.request.PayReq.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final PayType[] VALUES = values();

  public static PayType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PayType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:src.main.proto.PayType)
}

