// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

public interface RefundRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.RefundRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  int getChannelValue();
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  org.zhongweixian.request.Channel getChannel();

  /**
   * <pre>
   *商户订单号
   * </pre>
   *
   * <code>optional string orderNo = 2;</code>
   */
  java.lang.String getOrderNo();
  /**
   * <pre>
   *商户订单号
   * </pre>
   *
   * <code>optional string orderNo = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();

  /**
   * <pre>
   *交易平台订单
   * </pre>
   *
   * <code>optional string orderId = 3;</code>
   */
  java.lang.String getOrderId();
  /**
   * <pre>
   *交易平台订单
   * </pre>
   *
   * <code>optional string orderId = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <pre>
   *商户退款单号
   * </pre>
   *
   * <code>optional string refundNo = 4;</code>
   */
  java.lang.String getRefundNo();
  /**
   * <pre>
   *商户退款单号
   * </pre>
   *
   * <code>optional string refundNo = 4;</code>
   */
  com.google.protobuf.ByteString
      getRefundNoBytes();

  /**
   * <pre>
   *订单总金额
   * </pre>
   *
   * <code>optional int64 totalFee = 5;</code>
   */
  long getTotalFee();

  /**
   * <pre>
   *退款金额
   * </pre>
   *
   * <code>optional int64 refundFee = 6;</code>
   */
  long getRefundFee();

  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  java.lang.String getNotifyUrl();
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  com.google.protobuf.ByteString
      getNotifyUrlBytes();

  /**
   * <pre>
   *退款原因
   * </pre>
   *
   * <code>optional string refundDesc = 9;</code>
   */
  java.lang.String getRefundDesc();
  /**
   * <pre>
   *退款原因
   * </pre>
   *
   * <code>optional string refundDesc = 9;</code>
   */
  com.google.protobuf.ByteString
      getRefundDescBytes();
}
