// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

/**
 * <pre>
 **
 * 退款请求对象
 * </pre>
 *
 * Protobuf type {@code src.main.proto.RefundRequest}
 */
public  final class RefundRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:src.main.proto.RefundRequest)
    RefundRequestOrBuilder {
  // Use RefundRequest.newBuilder() to construct.
  private RefundRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RefundRequest() {
    channel_ = 0;
    orderNo_ = "";
    orderId_ = "";
    refundNo_ = "";
    totalFee_ = 0L;
    refundFee_ = 0L;
    notifyUrl_ = "";
    refundDesc_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RefundRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            channel_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            orderNo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            orderId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            refundNo_ = s;
            break;
          }
          case 40: {

            totalFee_ = input.readInt64();
            break;
          }
          case 48: {

            refundFee_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            notifyUrl_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            refundDesc_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.zhongweixian.request.PayReq.internal_static_src_main_proto_RefundRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.zhongweixian.request.PayReq.internal_static_src_main_proto_RefundRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.zhongweixian.request.RefundRequest.class, org.zhongweixian.request.RefundRequest.Builder.class);
  }

  public static final int CHANNEL_FIELD_NUMBER = 1;
  private int channel_;
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  public int getChannelValue() {
    return channel_;
  }
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  public org.zhongweixian.request.Channel getChannel() {
    org.zhongweixian.request.Channel result = org.zhongweixian.request.Channel.valueOf(channel_);
    return result == null ? org.zhongweixian.request.Channel.UNRECOGNIZED : result;
  }

  public static final int ORDERNO_FIELD_NUMBER = 2;
  private volatile java.lang.Object orderNo_;
  /**
   * <pre>
   *商户订单号
   * </pre>
   *
   * <code>optional string orderNo = 2;</code>
   */
  public java.lang.String getOrderNo() {
    java.lang.Object ref = orderNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *商户订单号
   * </pre>
   *
   * <code>optional string orderNo = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOrderNoBytes() {
    java.lang.Object ref = orderNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERID_FIELD_NUMBER = 3;
  private volatile java.lang.Object orderId_;
  /**
   * <pre>
   *交易平台订单
   * </pre>
   *
   * <code>optional string orderId = 3;</code>
   */
  public java.lang.String getOrderId() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *交易平台订单
   * </pre>
   *
   * <code>optional string orderId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    java.lang.Object ref = orderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFUNDNO_FIELD_NUMBER = 4;
  private volatile java.lang.Object refundNo_;
  /**
   * <pre>
   *商户退款单号
   * </pre>
   *
   * <code>optional string refundNo = 4;</code>
   */
  public java.lang.String getRefundNo() {
    java.lang.Object ref = refundNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refundNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *商户退款单号
   * </pre>
   *
   * <code>optional string refundNo = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRefundNoBytes() {
    java.lang.Object ref = refundNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refundNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALFEE_FIELD_NUMBER = 5;
  private long totalFee_;
  /**
   * <pre>
   *订单总金额
   * </pre>
   *
   * <code>optional int64 totalFee = 5;</code>
   */
  public long getTotalFee() {
    return totalFee_;
  }

  public static final int REFUNDFEE_FIELD_NUMBER = 6;
  private long refundFee_;
  /**
   * <pre>
   *退款金额
   * </pre>
   *
   * <code>optional int64 refundFee = 6;</code>
   */
  public long getRefundFee() {
    return refundFee_;
  }

  public static final int NOTIFYURL_FIELD_NUMBER = 7;
  private volatile java.lang.Object notifyUrl_;
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  public java.lang.String getNotifyUrl() {
    java.lang.Object ref = notifyUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notifyUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *回调通知地址
   * </pre>
   *
   * <code>optional string notifyUrl = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNotifyUrlBytes() {
    java.lang.Object ref = notifyUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notifyUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFUNDDESC_FIELD_NUMBER = 9;
  private volatile java.lang.Object refundDesc_;
  /**
   * <pre>
   *退款原因
   * </pre>
   *
   * <code>optional string refundDesc = 9;</code>
   */
  public java.lang.String getRefundDesc() {
    java.lang.Object ref = refundDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refundDesc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *退款原因
   * </pre>
   *
   * <code>optional string refundDesc = 9;</code>
   */
  public com.google.protobuf.ByteString
      getRefundDescBytes() {
    java.lang.Object ref = refundDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refundDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (channel_ != org.zhongweixian.request.Channel.ALI_PAY.getNumber()) {
      output.writeEnum(1, channel_);
    }
    if (!getOrderNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderNo_);
    }
    if (!getOrderIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orderId_);
    }
    if (!getRefundNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, refundNo_);
    }
    if (totalFee_ != 0L) {
      output.writeInt64(5, totalFee_);
    }
    if (refundFee_ != 0L) {
      output.writeInt64(6, refundFee_);
    }
    if (!getNotifyUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, notifyUrl_);
    }
    if (!getRefundDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, refundDesc_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (channel_ != org.zhongweixian.request.Channel.ALI_PAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, channel_);
    }
    if (!getOrderNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderNo_);
    }
    if (!getOrderIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orderId_);
    }
    if (!getRefundNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, refundNo_);
    }
    if (totalFee_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, totalFee_);
    }
    if (refundFee_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, refundFee_);
    }
    if (!getNotifyUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, notifyUrl_);
    }
    if (!getRefundDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, refundDesc_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.zhongweixian.request.RefundRequest)) {
      return super.equals(obj);
    }
    org.zhongweixian.request.RefundRequest other = (org.zhongweixian.request.RefundRequest) obj;

    boolean result = true;
    result = result && channel_ == other.channel_;
    result = result && getOrderNo()
        .equals(other.getOrderNo());
    result = result && getOrderId()
        .equals(other.getOrderId());
    result = result && getRefundNo()
        .equals(other.getRefundNo());
    result = result && (getTotalFee()
        == other.getTotalFee());
    result = result && (getRefundFee()
        == other.getRefundFee());
    result = result && getNotifyUrl()
        .equals(other.getNotifyUrl());
    result = result && getRefundDesc()
        .equals(other.getRefundDesc());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
    hash = (53 * hash) + channel_;
    hash = (37 * hash) + ORDERNO_FIELD_NUMBER;
    hash = (53 * hash) + getOrderNo().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    hash = (37 * hash) + REFUNDNO_FIELD_NUMBER;
    hash = (53 * hash) + getRefundNo().hashCode();
    hash = (37 * hash) + TOTALFEE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalFee());
    hash = (37 * hash) + REFUNDFEE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRefundFee());
    hash = (37 * hash) + NOTIFYURL_FIELD_NUMBER;
    hash = (53 * hash) + getNotifyUrl().hashCode();
    hash = (37 * hash) + REFUNDDESC_FIELD_NUMBER;
    hash = (53 * hash) + getRefundDesc().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.zhongweixian.request.RefundRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.request.RefundRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.RefundRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.zhongweixian.request.RefundRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.zhongweixian.request.RefundRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 退款请求对象
   * </pre>
   *
   * Protobuf type {@code src.main.proto.RefundRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:src.main.proto.RefundRequest)
      org.zhongweixian.request.RefundRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_RefundRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_RefundRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhongweixian.request.RefundRequest.class, org.zhongweixian.request.RefundRequest.Builder.class);
    }

    // Construct using org.zhongweixian.request.RefundRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      channel_ = 0;

      orderNo_ = "";

      orderId_ = "";

      refundNo_ = "";

      totalFee_ = 0L;

      refundFee_ = 0L;

      notifyUrl_ = "";

      refundDesc_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.zhongweixian.request.PayReq.internal_static_src_main_proto_RefundRequest_descriptor;
    }

    public org.zhongweixian.request.RefundRequest getDefaultInstanceForType() {
      return org.zhongweixian.request.RefundRequest.getDefaultInstance();
    }

    public org.zhongweixian.request.RefundRequest build() {
      org.zhongweixian.request.RefundRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.zhongweixian.request.RefundRequest buildPartial() {
      org.zhongweixian.request.RefundRequest result = new org.zhongweixian.request.RefundRequest(this);
      result.channel_ = channel_;
      result.orderNo_ = orderNo_;
      result.orderId_ = orderId_;
      result.refundNo_ = refundNo_;
      result.totalFee_ = totalFee_;
      result.refundFee_ = refundFee_;
      result.notifyUrl_ = notifyUrl_;
      result.refundDesc_ = refundDesc_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.zhongweixian.request.RefundRequest) {
        return mergeFrom((org.zhongweixian.request.RefundRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.zhongweixian.request.RefundRequest other) {
      if (other == org.zhongweixian.request.RefundRequest.getDefaultInstance()) return this;
      if (other.channel_ != 0) {
        setChannelValue(other.getChannelValue());
      }
      if (!other.getOrderNo().isEmpty()) {
        orderNo_ = other.orderNo_;
        onChanged();
      }
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        onChanged();
      }
      if (!other.getRefundNo().isEmpty()) {
        refundNo_ = other.refundNo_;
        onChanged();
      }
      if (other.getTotalFee() != 0L) {
        setTotalFee(other.getTotalFee());
      }
      if (other.getRefundFee() != 0L) {
        setRefundFee(other.getRefundFee());
      }
      if (!other.getNotifyUrl().isEmpty()) {
        notifyUrl_ = other.notifyUrl_;
        onChanged();
      }
      if (!other.getRefundDesc().isEmpty()) {
        refundDesc_ = other.refundDesc_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.zhongweixian.request.RefundRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.zhongweixian.request.RefundRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int channel_ = 0;
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public int getChannelValue() {
      return channel_;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public Builder setChannelValue(int value) {
      channel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public org.zhongweixian.request.Channel getChannel() {
      org.zhongweixian.request.Channel result = org.zhongweixian.request.Channel.valueOf(channel_);
      return result == null ? org.zhongweixian.request.Channel.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public Builder setChannel(org.zhongweixian.request.Channel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      channel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *支付渠道
     * </pre>
     *
     * <code>optional .src.main.proto.Channel channel = 1;</code>
     */
    public Builder clearChannel() {
      
      channel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object orderNo_ = "";
    /**
     * <pre>
     *商户订单号
     * </pre>
     *
     * <code>optional string orderNo = 2;</code>
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *商户订单号
     * </pre>
     *
     * <code>optional string orderNo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *商户订单号
     * </pre>
     *
     * <code>optional string orderNo = 2;</code>
     */
    public Builder setOrderNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户订单号
     * </pre>
     *
     * <code>optional string orderNo = 2;</code>
     */
    public Builder clearOrderNo() {
      
      orderNo_ = getDefaultInstance().getOrderNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户订单号
     * </pre>
     *
     * <code>optional string orderNo = 2;</code>
     */
    public Builder setOrderNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object orderId_ = "";
    /**
     * <pre>
     *交易平台订单
     * </pre>
     *
     * <code>optional string orderId = 3;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *交易平台订单
     * </pre>
     *
     * <code>optional string orderId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *交易平台订单
     * </pre>
     *
     * <code>optional string orderId = 3;</code>
     */
    public Builder setOrderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易平台订单
     * </pre>
     *
     * <code>optional string orderId = 3;</code>
     */
    public Builder clearOrderId() {
      
      orderId_ = getDefaultInstance().getOrderId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易平台订单
     * </pre>
     *
     * <code>optional string orderId = 3;</code>
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object refundNo_ = "";
    /**
     * <pre>
     *商户退款单号
     * </pre>
     *
     * <code>optional string refundNo = 4;</code>
     */
    public java.lang.String getRefundNo() {
      java.lang.Object ref = refundNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refundNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *商户退款单号
     * </pre>
     *
     * <code>optional string refundNo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRefundNoBytes() {
      java.lang.Object ref = refundNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refundNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *商户退款单号
     * </pre>
     *
     * <code>optional string refundNo = 4;</code>
     */
    public Builder setRefundNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refundNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户退款单号
     * </pre>
     *
     * <code>optional string refundNo = 4;</code>
     */
    public Builder clearRefundNo() {
      
      refundNo_ = getDefaultInstance().getRefundNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *商户退款单号
     * </pre>
     *
     * <code>optional string refundNo = 4;</code>
     */
    public Builder setRefundNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refundNo_ = value;
      onChanged();
      return this;
    }

    private long totalFee_ ;
    /**
     * <pre>
     *订单总金额
     * </pre>
     *
     * <code>optional int64 totalFee = 5;</code>
     */
    public long getTotalFee() {
      return totalFee_;
    }
    /**
     * <pre>
     *订单总金额
     * </pre>
     *
     * <code>optional int64 totalFee = 5;</code>
     */
    public Builder setTotalFee(long value) {
      
      totalFee_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *订单总金额
     * </pre>
     *
     * <code>optional int64 totalFee = 5;</code>
     */
    public Builder clearTotalFee() {
      
      totalFee_ = 0L;
      onChanged();
      return this;
    }

    private long refundFee_ ;
    /**
     * <pre>
     *退款金额
     * </pre>
     *
     * <code>optional int64 refundFee = 6;</code>
     */
    public long getRefundFee() {
      return refundFee_;
    }
    /**
     * <pre>
     *退款金额
     * </pre>
     *
     * <code>optional int64 refundFee = 6;</code>
     */
    public Builder setRefundFee(long value) {
      
      refundFee_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *退款金额
     * </pre>
     *
     * <code>optional int64 refundFee = 6;</code>
     */
    public Builder clearRefundFee() {
      
      refundFee_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object notifyUrl_ = "";
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public java.lang.String getNotifyUrl() {
      java.lang.Object ref = notifyUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notifyUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNotifyUrlBytes() {
      java.lang.Object ref = notifyUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notifyUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public Builder setNotifyUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notifyUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public Builder clearNotifyUrl() {
      
      notifyUrl_ = getDefaultInstance().getNotifyUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调通知地址
     * </pre>
     *
     * <code>optional string notifyUrl = 7;</code>
     */
    public Builder setNotifyUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notifyUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object refundDesc_ = "";
    /**
     * <pre>
     *退款原因
     * </pre>
     *
     * <code>optional string refundDesc = 9;</code>
     */
    public java.lang.String getRefundDesc() {
      java.lang.Object ref = refundDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refundDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *退款原因
     * </pre>
     *
     * <code>optional string refundDesc = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRefundDescBytes() {
      java.lang.Object ref = refundDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refundDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *退款原因
     * </pre>
     *
     * <code>optional string refundDesc = 9;</code>
     */
    public Builder setRefundDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refundDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *退款原因
     * </pre>
     *
     * <code>optional string refundDesc = 9;</code>
     */
    public Builder clearRefundDesc() {
      
      refundDesc_ = getDefaultInstance().getRefundDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *退款原因
     * </pre>
     *
     * <code>optional string refundDesc = 9;</code>
     */
    public Builder setRefundDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refundDesc_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:src.main.proto.RefundRequest)
  }

  // @@protoc_insertion_point(class_scope:src.main.proto.RefundRequest)
  private static final org.zhongweixian.request.RefundRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.zhongweixian.request.RefundRequest();
  }

  public static org.zhongweixian.request.RefundRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RefundRequest>
      PARSER = new com.google.protobuf.AbstractParser<RefundRequest>() {
    public RefundRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RefundRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RefundRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RefundRequest> getParserForType() {
    return PARSER;
  }

  public org.zhongweixian.request.RefundRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

