// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayReq.proto

package org.zhongweixian.request;

public interface VerifyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.VerifyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  int getChannelValue();
  /**
   * <pre>
   *支付渠道
   * </pre>
   *
   * <code>optional .src.main.proto.Channel channel = 1;</code>
   */
  org.zhongweixian.request.Channel getChannel();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional string body = 2;</code>
   */
  java.lang.String getBody();
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string body = 2;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional string signature = 3;</code>
   */
  java.lang.String getSignature();
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string signature = 3;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional string key = 4;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   * </pre>
   *
   * <code>optional string key = 4;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
